Sync with latest blazesym repo
The top upstream blazesym commit is

  commit 30b803d861e6609f2ca3e84a3e7e0eb2c41ef5bb (HEAD -> main, origin/main, origin/HEAD)
  Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
  Date:   Wed Jan 14 14:05:06 2026 +0000

    build(deps): bump zip from 7.0.0 to 7.1.0

diff --git a/libbpf-tools/Makefile b/libbpf-tools/Makefile
--- a/libbpf-tools/Makefile
+++ b/libbpf-tools/Makefile
@@ -165,7 +165,7 @@ clean:
 	$(Q)rm -rf $(OUTPUT) $(APPS) $(APP_ALIASES)
 
 $(LIBBLAZESYM_SRC)::
-	$(Q)cd blazesym && cargo build --release --features=cheader
+	$(Q)cd blazesym && cargo build --release
 
 $(OUTPUT)/libblazesym.a: $(LIBBLAZESYM_SRC) | $(OUTPUT)
 	$(call msg,LIB,$@)
@@ -173,7 +173,14 @@ $(OUTPUT)/libblazesym.a: $(LIBBLAZESYM_SRC) | $(OUTPUT)
 
 $(OUTPUT)/blazesym.h: $(LIBBLAZESYM_SRC) | $(OUTPUT)
 	$(call msg,INC,$@)
-	$(Q)cp blazesym/target/release/blazesym.h $@
+	$(Q)if [ -f blazesym/target/release/blazesym.h ]; then \
+		cp blazesym/target/release/blazesym.h $@; \
+	elif [ -f blazesym/include/blazesym.h ]; then \
+		cp blazesym/include/blazesym.h $@; \
+	else \
+		echo "Error: blazesym.h not found. Please check blazesym version."; \
+		exit 1; \
+	fi
 
 $(OUTPUT) $(OUTPUT)/libbpf $(BPFTOOL_OUTPUT):
 	$(call msg,MKDIR,$@)
